master Added `luarocks init`

diff --git a/.github/workflows/dependency-updater.yml b/.github/workflows/dependency-updater.yml
--- a/.github/workflows/dependency-updater.yml
+++ b/.github/workflows/dependency-updater.yml
@@ -13,13 +13,61 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Install and init luarocks
+        shell: cmd
+        run: |
+          cd ${{ github.workspace}}\mods\noita-mp\
+          set INIT_PATH=%CD%
+          REM // resolve absolute path
+          set REL_PATH=..\..\.building\luarocks-3.9.1-windows-32
+          set ABS_PATH=
+          rem // Save current directory and change to target directory
+          pushd %REL_PATH%
+          rem // Save value of CD variable (current directory)
+          set ABS_PATH=%CD%
+          rem // Restore original directory
+          popd
+          echo Relative path: %REL_PATH%
+          echo Maps to path: %ABS_PATH%
+        
+          REM // init luarocks
+          %ABS_PATH%\luarocks --lua-dir="${{ github.workspace}}\LuaJIT-2.0.4" --lua-version="5.1" init noita-mp --output="${{ github.workspace}}\mods\noita-mp" --homepage="https://github.com/Ismoh/NoitaMP" --lua-versions="5.1" --license="GNU GPL v3"
+        
+          REM // change luarocks projects config
+          %ABS_PATH%\luarocks config --scope="project" lua_interpreter luajit.exe
+          %ABS_PATH%\luarocks config --scope="project" lua_dir ${{ github.workspace}}\LuaJIT-2.0.4
+          %ABS_PATH%\luarocks config --scope="project" variables.LUA_BINDIR ${{ github.workspace}}\LuaJIT-2.0.4\bin
+          %ABS_PATH%\luarocks config --scope="project" variables.LUA_DIR ${{ github.workspace}}\LuaJIT-2.0.4
+          %ABS_PATH%\luarocks config --scope="project" variables.LUA_INCDIR ${{ github.workspace}}\LuaJIT-2.0.4\include
+          %ABS_PATH%\luarocks config --scope="project" variables.CFLAGS "GODDAMNIT"
+          %ABS_PATH%\luarocks config
+  
+          if exist lua.bat (
+            echo "LuaRocks project init successfully"
+          ) else (
+            echo "::error::LuaRocks project init failed. Unable to find lua.bat"
+            exit 1
+          )
+          if exist luarocks.bat (
+            echo "LuaRocks project init successfully"
+          ) else (
+            echo "::error::LuaRocks project init failed. Unable to find luarocks.bat"
+            exit 1
+          )
+      
+      - name: Fix LuaRocks bug
+        run: |
+          cd ${{ github.workspace}}\mods\noita-mp\.luarocks
+          sed -i 's/GODDAMNIT/\-v \-O2/g' config-5.1.lua
+          cat config-5.1.lua
+
       - name: Update LuaRocks
         shell: cmd
         run: |
           git checkout -b dependency-updates master || git checkout dependency-updates
           call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86 10.0.22000.0 -vcvars_ver=14
           cd ${{ github.workspace }}\mods\noita-mp\
-          luarocks.bat install --only-deps noita-mp-3.0.0-3.rockspec
+          luarocks install --only-deps noita-mp-3.0.0-3.rockspec
           git config --local user.email "action@github.com"
           git config --local user.name "github-actions"
           git commit -m "Update LuaRocks dependencies" -a || echo "No changes to commit"
