#92 Testing failed and errored unit tests.

diff --git a/.github/workflows/windows-latest-lua-unit-testing.yml b/.github/workflows/windows-latest-lua-unit-testing.yml
--- a/.github/workflows/windows-latest-lua-unit-testing.yml
+++ b/.github/workflows/windows-latest-lua-unit-testing.yml
@@ -122,14 +122,22 @@ jobs:
           type result.log
           
       - name: Failed unit tests?
-        shell: sh
         run: |
           cd ${{ github.workspace}}/mods/noita-mp
-          error=$(cat result.log | sed 's/.*error //' | cut -d " " -f 1)
-          echo "$error"
-          fail=$(cat result.log | sed 's/.*failures //' | cut -d " " -f 1)
-
-          echo "$fail"
+          
+          for /F "tokens=9 delims= " %a in ('findstr /I "failure*" result.log') do set "failCount=%a"
+          echo "failCount: %failCount%"
+          if NOT %failCount% == 0 (
+            echo "::error title=LuaUnit tests failed::%failCount% failures occurred!"
+            exit 1
+          )
+  
+          for /F "tokens=9 delims= " %a in ('findstr /I "error*" result.log') do set "errorCount=%a"
+          echo "errorCount: %errorCount%"
+          if NOT %errorCount% == 0 (
+            echo "::error title=LuaUnit tests errored::%errorCount% errors occurred!"
+            exit 1
+          )
       
       - name: Install dependencies
         shell: cmd
